micronaut:
  application:
    name: keyManagerRest
  server:
    port: ${SERVER_PORT:8080}

api.version: v1

jackson:
  date-format: yyyy-MM-dd HH:mm:ss
  serializationInclusion: ALWAYS

grpc:
  client:
    plaintext: true
    max-retry-attempts: 10
  channels:
    keyManager:
      address: '${KEY_MANAGER_HOST:localhost}:${KEY_MANAGER_PORT:50051}'
